### PR TITLE
mozinfo python 3 compatible

### PR DESCRIPTION
**Pull request by peterbe**
This (selfishly) fixes `mozinfo` so it works in Python 2.7 and 3.5 and 3.6 (because those are the ones I had to test with)

```
▶ python mozinfo/mozinfo/mozinfo.py
version: OS X 10.13.6
os: mac
bits: 64
processor: x86_64
```
```
▶ python3.5 mozinfo/mozinfo/mozinfo.py
os: mac
version: OS X 10.13.6
bits: 64
processor: x86_64
```
```
▶ python3.6 mozinfo/mozinfo/mozinfo.py
os: mac
processor: x86_64
version: OS X 10.13.6
bits: 64
```

### CODE REVIEW

**Comment by peterbe** [comment]
@choller What would it take to get this into pypi?

**Comment by choller** [comment]
@peterbe Thanks for the contribution but I do not maintain mozbase, I only forked it (long time ago). I think mozbase itself has been deprecated by Mozilla. The best you can do is check with the original repository (mozilla/mozbase-deprecated), maybe it is already py3 compatible. Sorry I cannot help you further here.

**Comment by peterbe** [comment]
Ah. I see. Either way, I'll try poking around. My goal is to make `mozdownload` work in Python 3. Trying to help https://github.com/mozilla/mozdownload/issues/415

**Comment by choller** [comment]
@peterbe You might want to look into fuzzfetch (https://github.com/MozillaSecurity/fuzzfetch). That is what we currently use in fuzzing to download Firefox builds from Taskcluster. Maybe this will already do what you need.

**Comment by peterbe** [comment]
I'm looking at it but it seems quite unrelated. How did you mean I could use that to download and install firefox?

**Comment by peterbe** [comment]
Anyway, I managed to get it to work with https://www.npmjs.com/package/get-firefox

This works now:
```
apt install firefox-esr
npm install -g get-firefox
get-firefox -e
./firefox/firefox --version
```

**Pull request closed without merging**
